// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartUnitCalculator.Database;

#nullable disable

namespace SmartUnitCalculator.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220713171631_AddBasicSeed")]
    partial class AddBasicSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Multiplier")
                        .HasPrecision(38, 19)
                        .HasColumnType("decimal(38,19)");

                    b.Property<int>("ResultUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("ResultUnitId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseValue")
                        .HasPrecision(38, 19)
                        .HasColumnType("decimal(38,19)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ResultUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("ResultValue")
                        .HasPrecision(38, 19)
                        .HasColumnType("decimal(38,19)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("ResultUnitId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "miligram",
                            Priority = 10,
                            Symbol = "mg",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "gram",
                            Priority = 20,
                            Symbol = "g",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 3,
                            Name = "dekagram",
                            Priority = 30,
                            Symbol = "dag",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 4,
                            Name = "kilogram",
                            Priority = 40,
                            Symbol = "kg",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 5,
                            Name = "tona",
                            Priority = 50,
                            Symbol = "t",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 6,
                            Name = "milimetr",
                            Priority = 10,
                            Symbol = "mm",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 7,
                            Name = "centrymetr",
                            Priority = 20,
                            Symbol = "cm",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 8,
                            Name = "decymetr",
                            Priority = 30,
                            Symbol = "dm",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 9,
                            Name = "metr",
                            Priority = 40,
                            Symbol = "m",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 10,
                            Name = "kilometr",
                            Priority = 50,
                            Symbol = "km",
                            TypeName = "Objętość"
                        },
                        new
                        {
                            Id = 11,
                            Name = "pikolitr",
                            Priority = 10,
                            Symbol = "pl",
                            TypeName = "Objętość"
                        },
                        new
                        {
                            Id = 12,
                            Name = "mililitr",
                            Priority = 20,
                            Symbol = "ml",
                            TypeName = "Objętość"
                        },
                        new
                        {
                            Id = 13,
                            Name = "litr",
                            Priority = 30,
                            Symbol = "l",
                            TypeName = "Objętość"
                        });
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.UnitType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            Name = "Waga",
                            Priority = 10
                        },
                        new
                        {
                            Name = "Długość",
                            Priority = 20
                        },
                        new
                        {
                            Name = "Objętość",
                            Priority = 30
                        },
                        new
                        {
                            Name = "Temperatura",
                            Priority = 40
                        },
                        new
                        {
                            Name = "Czas",
                            Priority = 50
                        });
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Calculation", b =>
                {
                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "BaseUnit")
                        .WithMany("Calculations")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "ResultUnit")
                        .WithMany()
                        .HasForeignKey("ResultUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("ResultUnit");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.History", b =>
                {
                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "ResultUnit")
                        .WithMany()
                        .HasForeignKey("ResultUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("ResultUnit");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Unit", b =>
                {
                    b.HasOne("SmartUnitCalculator.Database.Models.UnitType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Unit", b =>
                {
                    b.Navigation("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
