// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartUnitCalculator.Database;

#nullable disable

namespace SmartUnitCalculator.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220714191701_AddSeed")]
    partial class AddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Multiplier")
                        .HasPrecision(38, 19)
                        .HasColumnType("decimal(38,19)");

                    b.Property<int>("ResultUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("ResultUnitId");

                    b.ToTable("Calculations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUnitId = 1,
                            Multiplier = 0.001m,
                            ResultUnitId = 2
                        },
                        new
                        {
                            Id = 2,
                            BaseUnitId = 1,
                            Multiplier = 0.0001m,
                            ResultUnitId = 3
                        },
                        new
                        {
                            Id = 3,
                            BaseUnitId = 1,
                            Multiplier = 0.000001m,
                            ResultUnitId = 4
                        },
                        new
                        {
                            Id = 4,
                            BaseUnitId = 1,
                            Multiplier = 0.000000001m,
                            ResultUnitId = 5
                        },
                        new
                        {
                            Id = 5,
                            BaseUnitId = 2,
                            Multiplier = 1000m,
                            ResultUnitId = 1
                        },
                        new
                        {
                            Id = 6,
                            BaseUnitId = 2,
                            Multiplier = 0.1m,
                            ResultUnitId = 3
                        },
                        new
                        {
                            Id = 7,
                            BaseUnitId = 2,
                            Multiplier = 0.001m,
                            ResultUnitId = 4
                        },
                        new
                        {
                            Id = 8,
                            BaseUnitId = 2,
                            Multiplier = 0.000001m,
                            ResultUnitId = 5
                        },
                        new
                        {
                            Id = 9,
                            BaseUnitId = 3,
                            Multiplier = 10000m,
                            ResultUnitId = 1
                        },
                        new
                        {
                            Id = 10,
                            BaseUnitId = 3,
                            Multiplier = 10m,
                            ResultUnitId = 2
                        },
                        new
                        {
                            Id = 11,
                            BaseUnitId = 3,
                            Multiplier = 0.01m,
                            ResultUnitId = 4
                        },
                        new
                        {
                            Id = 12,
                            BaseUnitId = 3,
                            Multiplier = 0.00001m,
                            ResultUnitId = 5
                        },
                        new
                        {
                            Id = 13,
                            BaseUnitId = 4,
                            Multiplier = 1000000m,
                            ResultUnitId = 1
                        },
                        new
                        {
                            Id = 14,
                            BaseUnitId = 4,
                            Multiplier = 1000m,
                            ResultUnitId = 2
                        },
                        new
                        {
                            Id = 15,
                            BaseUnitId = 4,
                            Multiplier = 100m,
                            ResultUnitId = 3
                        },
                        new
                        {
                            Id = 16,
                            BaseUnitId = 4,
                            Multiplier = 0.001m,
                            ResultUnitId = 5
                        },
                        new
                        {
                            Id = 17,
                            BaseUnitId = 5,
                            Multiplier = 1000000000m,
                            ResultUnitId = 1
                        },
                        new
                        {
                            Id = 18,
                            BaseUnitId = 5,
                            Multiplier = 1000000m,
                            ResultUnitId = 2
                        },
                        new
                        {
                            Id = 19,
                            BaseUnitId = 5,
                            Multiplier = 100000m,
                            ResultUnitId = 3
                        },
                        new
                        {
                            Id = 20,
                            BaseUnitId = 5,
                            Multiplier = 1000m,
                            ResultUnitId = 4
                        },
                        new
                        {
                            Id = 21,
                            BaseUnitId = 6,
                            Multiplier = 0.1m,
                            ResultUnitId = 7
                        },
                        new
                        {
                            Id = 22,
                            BaseUnitId = 6,
                            Multiplier = 0.01m,
                            ResultUnitId = 8
                        },
                        new
                        {
                            Id = 23,
                            BaseUnitId = 6,
                            Multiplier = 0.001m,
                            ResultUnitId = 9
                        },
                        new
                        {
                            Id = 24,
                            BaseUnitId = 6,
                            Multiplier = 0.000001m,
                            ResultUnitId = 10
                        },
                        new
                        {
                            Id = 25,
                            BaseUnitId = 7,
                            Multiplier = 10m,
                            ResultUnitId = 6
                        },
                        new
                        {
                            Id = 26,
                            BaseUnitId = 7,
                            Multiplier = 0.1m,
                            ResultUnitId = 8
                        },
                        new
                        {
                            Id = 27,
                            BaseUnitId = 7,
                            Multiplier = 0.01m,
                            ResultUnitId = 9
                        },
                        new
                        {
                            Id = 28,
                            BaseUnitId = 7,
                            Multiplier = 0.00001m,
                            ResultUnitId = 10
                        },
                        new
                        {
                            Id = 29,
                            BaseUnitId = 8,
                            Multiplier = 100m,
                            ResultUnitId = 6
                        },
                        new
                        {
                            Id = 30,
                            BaseUnitId = 8,
                            Multiplier = 10m,
                            ResultUnitId = 7
                        },
                        new
                        {
                            Id = 31,
                            BaseUnitId = 8,
                            Multiplier = 0.1m,
                            ResultUnitId = 9
                        },
                        new
                        {
                            Id = 32,
                            BaseUnitId = 8,
                            Multiplier = 0.0001m,
                            ResultUnitId = 10
                        },
                        new
                        {
                            Id = 33,
                            BaseUnitId = 9,
                            Multiplier = 1000m,
                            ResultUnitId = 6
                        },
                        new
                        {
                            Id = 34,
                            BaseUnitId = 9,
                            Multiplier = 100m,
                            ResultUnitId = 7
                        },
                        new
                        {
                            Id = 35,
                            BaseUnitId = 9,
                            Multiplier = 10m,
                            ResultUnitId = 8
                        },
                        new
                        {
                            Id = 36,
                            BaseUnitId = 9,
                            Multiplier = 0.001m,
                            ResultUnitId = 10
                        },
                        new
                        {
                            Id = 37,
                            BaseUnitId = 10,
                            Multiplier = 1000000m,
                            ResultUnitId = 6
                        },
                        new
                        {
                            Id = 38,
                            BaseUnitId = 10,
                            Multiplier = 100000m,
                            ResultUnitId = 7
                        },
                        new
                        {
                            Id = 39,
                            BaseUnitId = 10,
                            Multiplier = 10000m,
                            ResultUnitId = 8
                        },
                        new
                        {
                            Id = 40,
                            BaseUnitId = 10,
                            Multiplier = 1000m,
                            ResultUnitId = 9
                        },
                        new
                        {
                            Id = 41,
                            BaseUnitId = 11,
                            Multiplier = 0.000000001m,
                            ResultUnitId = 12
                        },
                        new
                        {
                            Id = 42,
                            BaseUnitId = 11,
                            Multiplier = 0.000000000001m,
                            ResultUnitId = 13
                        },
                        new
                        {
                            Id = 43,
                            BaseUnitId = 12,
                            Multiplier = 1000000000m,
                            ResultUnitId = 11
                        },
                        new
                        {
                            Id = 44,
                            BaseUnitId = 12,
                            Multiplier = 0.001m,
                            ResultUnitId = 13
                        },
                        new
                        {
                            Id = 45,
                            BaseUnitId = 13,
                            Multiplier = 1000000000000m,
                            ResultUnitId = 11
                        },
                        new
                        {
                            Id = 46,
                            BaseUnitId = 13,
                            Multiplier = 1000m,
                            ResultUnitId = 12
                        },
                        new
                        {
                            Id = 47,
                            BaseUnitId = 14,
                            Multiplier = 0.125m,
                            ResultUnitId = 15
                        },
                        new
                        {
                            Id = 48,
                            BaseUnitId = 14,
                            Multiplier = 0.001m,
                            ResultUnitId = 16
                        },
                        new
                        {
                            Id = 49,
                            BaseUnitId = 14,
                            Multiplier = 0.000125m,
                            ResultUnitId = 17
                        },
                        new
                        {
                            Id = 50,
                            BaseUnitId = 14,
                            Multiplier = 0.000001m,
                            ResultUnitId = 18
                        },
                        new
                        {
                            Id = 51,
                            BaseUnitId = 14,
                            Multiplier = 0.000000125m,
                            ResultUnitId = 19
                        },
                        new
                        {
                            Id = 52,
                            BaseUnitId = 14,
                            Multiplier = 0.000000001m,
                            ResultUnitId = 20
                        },
                        new
                        {
                            Id = 53,
                            BaseUnitId = 14,
                            Multiplier = 0.000000000125m,
                            ResultUnitId = 21
                        },
                        new
                        {
                            Id = 54,
                            BaseUnitId = 14,
                            Multiplier = 0.000000000001m,
                            ResultUnitId = 22
                        },
                        new
                        {
                            Id = 55,
                            BaseUnitId = 14,
                            Multiplier = 0.000000000000125m,
                            ResultUnitId = 23
                        },
                        new
                        {
                            Id = 56,
                            BaseUnitId = 15,
                            Multiplier = 8m,
                            ResultUnitId = 14
                        },
                        new
                        {
                            Id = 57,
                            BaseUnitId = 15,
                            Multiplier = 0.008m,
                            ResultUnitId = 16
                        },
                        new
                        {
                            Id = 58,
                            BaseUnitId = 15,
                            Multiplier = 0.001m,
                            ResultUnitId = 17
                        },
                        new
                        {
                            Id = 59,
                            BaseUnitId = 15,
                            Multiplier = 0.000008m,
                            ResultUnitId = 18
                        },
                        new
                        {
                            Id = 60,
                            BaseUnitId = 15,
                            Multiplier = 0.000001m,
                            ResultUnitId = 19
                        },
                        new
                        {
                            Id = 61,
                            BaseUnitId = 15,
                            Multiplier = 0.000000008m,
                            ResultUnitId = 20
                        },
                        new
                        {
                            Id = 62,
                            BaseUnitId = 15,
                            Multiplier = 0.000000001m,
                            ResultUnitId = 21
                        },
                        new
                        {
                            Id = 63,
                            BaseUnitId = 15,
                            Multiplier = 0.000000000008m,
                            ResultUnitId = 22
                        },
                        new
                        {
                            Id = 64,
                            BaseUnitId = 15,
                            Multiplier = 0.000000000001m,
                            ResultUnitId = 23
                        },
                        new
                        {
                            Id = 65,
                            BaseUnitId = 16,
                            Multiplier = 1000m,
                            ResultUnitId = 14
                        },
                        new
                        {
                            Id = 66,
                            BaseUnitId = 16,
                            Multiplier = 125m,
                            ResultUnitId = 15
                        },
                        new
                        {
                            Id = 67,
                            BaseUnitId = 16,
                            Multiplier = 0.125m,
                            ResultUnitId = 17
                        },
                        new
                        {
                            Id = 68,
                            BaseUnitId = 16,
                            Multiplier = 0.001m,
                            ResultUnitId = 18
                        },
                        new
                        {
                            Id = 69,
                            BaseUnitId = 16,
                            Multiplier = 0.000125m,
                            ResultUnitId = 19
                        },
                        new
                        {
                            Id = 70,
                            BaseUnitId = 16,
                            Multiplier = 0.000001m,
                            ResultUnitId = 20
                        },
                        new
                        {
                            Id = 71,
                            BaseUnitId = 16,
                            Multiplier = 0.000000125m,
                            ResultUnitId = 21
                        },
                        new
                        {
                            Id = 72,
                            BaseUnitId = 16,
                            Multiplier = 0.000000001m,
                            ResultUnitId = 22
                        },
                        new
                        {
                            Id = 73,
                            BaseUnitId = 16,
                            Multiplier = 0.000000000125m,
                            ResultUnitId = 23
                        },
                        new
                        {
                            Id = 74,
                            BaseUnitId = 17,
                            Multiplier = 8000m,
                            ResultUnitId = 14
                        },
                        new
                        {
                            Id = 75,
                            BaseUnitId = 17,
                            Multiplier = 1000m,
                            ResultUnitId = 15
                        },
                        new
                        {
                            Id = 76,
                            BaseUnitId = 17,
                            Multiplier = 8m,
                            ResultUnitId = 16
                        },
                        new
                        {
                            Id = 77,
                            BaseUnitId = 17,
                            Multiplier = 0.008m,
                            ResultUnitId = 18
                        },
                        new
                        {
                            Id = 78,
                            BaseUnitId = 17,
                            Multiplier = 0.001m,
                            ResultUnitId = 19
                        },
                        new
                        {
                            Id = 79,
                            BaseUnitId = 17,
                            Multiplier = 0.000008m,
                            ResultUnitId = 20
                        },
                        new
                        {
                            Id = 80,
                            BaseUnitId = 17,
                            Multiplier = 0.000001m,
                            ResultUnitId = 21
                        },
                        new
                        {
                            Id = 81,
                            BaseUnitId = 17,
                            Multiplier = 0.000000008m,
                            ResultUnitId = 22
                        },
                        new
                        {
                            Id = 82,
                            BaseUnitId = 17,
                            Multiplier = 0.000000001m,
                            ResultUnitId = 23
                        },
                        new
                        {
                            Id = 83,
                            BaseUnitId = 18,
                            Multiplier = 1000000m,
                            ResultUnitId = 14
                        },
                        new
                        {
                            Id = 84,
                            BaseUnitId = 18,
                            Multiplier = 125000m,
                            ResultUnitId = 15
                        },
                        new
                        {
                            Id = 85,
                            BaseUnitId = 18,
                            Multiplier = 1000m,
                            ResultUnitId = 16
                        },
                        new
                        {
                            Id = 86,
                            BaseUnitId = 18,
                            Multiplier = 125m,
                            ResultUnitId = 17
                        },
                        new
                        {
                            Id = 87,
                            BaseUnitId = 18,
                            Multiplier = 0.125m,
                            ResultUnitId = 19
                        },
                        new
                        {
                            Id = 88,
                            BaseUnitId = 18,
                            Multiplier = 0.001m,
                            ResultUnitId = 20
                        },
                        new
                        {
                            Id = 89,
                            BaseUnitId = 18,
                            Multiplier = 0.000125m,
                            ResultUnitId = 21
                        },
                        new
                        {
                            Id = 90,
                            BaseUnitId = 18,
                            Multiplier = 0.000001m,
                            ResultUnitId = 22
                        },
                        new
                        {
                            Id = 91,
                            BaseUnitId = 18,
                            Multiplier = 0.000000125m,
                            ResultUnitId = 23
                        },
                        new
                        {
                            Id = 92,
                            BaseUnitId = 19,
                            Multiplier = 8000000m,
                            ResultUnitId = 14
                        },
                        new
                        {
                            Id = 93,
                            BaseUnitId = 19,
                            Multiplier = 1000000m,
                            ResultUnitId = 15
                        },
                        new
                        {
                            Id = 94,
                            BaseUnitId = 19,
                            Multiplier = 8000m,
                            ResultUnitId = 16
                        },
                        new
                        {
                            Id = 95,
                            BaseUnitId = 19,
                            Multiplier = 1000m,
                            ResultUnitId = 17
                        },
                        new
                        {
                            Id = 96,
                            BaseUnitId = 19,
                            Multiplier = 8m,
                            ResultUnitId = 18
                        },
                        new
                        {
                            Id = 97,
                            BaseUnitId = 19,
                            Multiplier = 0.008m,
                            ResultUnitId = 20
                        },
                        new
                        {
                            Id = 98,
                            BaseUnitId = 19,
                            Multiplier = 0.001m,
                            ResultUnitId = 21
                        },
                        new
                        {
                            Id = 99,
                            BaseUnitId = 19,
                            Multiplier = 0.000008m,
                            ResultUnitId = 22
                        },
                        new
                        {
                            Id = 100,
                            BaseUnitId = 19,
                            Multiplier = 0.000001m,
                            ResultUnitId = 23
                        });
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseValue")
                        .HasPrecision(38, 19)
                        .HasColumnType("decimal(38,19)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ResultUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("ResultValue")
                        .HasPrecision(38, 19)
                        .HasColumnType("decimal(38,19)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("ResultUnitId");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUnitId = 3,
                            BaseValue = 25m,
                            Created = new DateTime(2022, 7, 2, 12, 51, 2, 0, DateTimeKind.Unspecified),
                            ResultUnitId = 5,
                            ResultValue = 0.00025m
                        },
                        new
                        {
                            Id = 2,
                            BaseUnitId = 3,
                            BaseValue = 25m,
                            Created = new DateTime(2022, 7, 2, 12, 51, 59, 0, DateTimeKind.Unspecified),
                            ResultUnitId = 4,
                            ResultValue = 0.25m
                        },
                        new
                        {
                            Id = 3,
                            BaseUnitId = 4,
                            BaseValue = 1m,
                            Created = new DateTime(2022, 7, 3, 9, 30, 51, 0, DateTimeKind.Unspecified),
                            ResultUnitId = 2,
                            ResultValue = 1000m
                        },
                        new
                        {
                            Id = 4,
                            BaseUnitId = 4,
                            BaseValue = 1.24m,
                            Created = new DateTime(2022, 7, 4, 21, 11, 21, 0, DateTimeKind.Unspecified),
                            ResultUnitId = 2,
                            ResultValue = 1240m
                        });
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "miligram",
                            Priority = 10,
                            Symbol = "mg",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "gram",
                            Priority = 20,
                            Symbol = "g",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 3,
                            Name = "dekagram",
                            Priority = 30,
                            Symbol = "dag",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 4,
                            Name = "kilogram",
                            Priority = 40,
                            Symbol = "kg",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 5,
                            Name = "tona",
                            Priority = 50,
                            Symbol = "t",
                            TypeName = "Waga"
                        },
                        new
                        {
                            Id = 6,
                            Name = "milimetr",
                            Priority = 10,
                            Symbol = "mm",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 7,
                            Name = "centrymetr",
                            Priority = 20,
                            Symbol = "cm",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 8,
                            Name = "decymetr",
                            Priority = 30,
                            Symbol = "dm",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 9,
                            Name = "metr",
                            Priority = 40,
                            Symbol = "m",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 10,
                            Name = "kilometr",
                            Priority = 50,
                            Symbol = "km",
                            TypeName = "Długość"
                        },
                        new
                        {
                            Id = 11,
                            Name = "pikolitr",
                            Priority = 10,
                            Symbol = "pl",
                            TypeName = "Objętość"
                        },
                        new
                        {
                            Id = 12,
                            Name = "mililitr",
                            Priority = 20,
                            Symbol = "ml",
                            TypeName = "Objętość"
                        },
                        new
                        {
                            Id = 13,
                            Name = "litr",
                            Priority = 30,
                            Symbol = "l",
                            TypeName = "Objętość"
                        },
                        new
                        {
                            Id = 14,
                            Name = "bit",
                            Priority = 10,
                            Symbol = "b",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 15,
                            Name = "bajt",
                            Priority = 20,
                            Symbol = "B",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 16,
                            Name = "kilobit",
                            Priority = 30,
                            Symbol = "Kb",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 17,
                            Name = "kilobajt",
                            Priority = 40,
                            Symbol = "KB",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 18,
                            Name = "maegabit",
                            Priority = 50,
                            Symbol = "Mb",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 19,
                            Name = "megabajt",
                            Priority = 60,
                            Symbol = "MB",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 20,
                            Name = "gigabit",
                            Priority = 70,
                            Symbol = "Gb",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 21,
                            Name = "gigabajt",
                            Priority = 80,
                            Symbol = "GB",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 22,
                            Name = "terabit",
                            Priority = 90,
                            Symbol = "Tb",
                            TypeName = "Pamięć"
                        },
                        new
                        {
                            Id = 23,
                            Name = "terabajt",
                            Priority = 100,
                            Symbol = "TB",
                            TypeName = "Pamięć"
                        });
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.UnitType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            Name = "Waga",
                            Priority = 10
                        },
                        new
                        {
                            Name = "Długość",
                            Priority = 20
                        },
                        new
                        {
                            Name = "Objętość",
                            Priority = 30
                        },
                        new
                        {
                            Name = "Pamięć",
                            Priority = 40
                        });
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Calculation", b =>
                {
                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "BaseUnit")
                        .WithMany("Calculations")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "ResultUnit")
                        .WithMany()
                        .HasForeignKey("ResultUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("ResultUnit");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.History", b =>
                {
                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartUnitCalculator.Database.Models.Unit", "ResultUnit")
                        .WithMany()
                        .HasForeignKey("ResultUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");

                    b.Navigation("ResultUnit");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Unit", b =>
                {
                    b.HasOne("SmartUnitCalculator.Database.Models.UnitType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SmartUnitCalculator.Database.Models.Unit", b =>
                {
                    b.Navigation("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
